= golang-formula

https://travis-ci.com/saltstack-formulas/golang-formula[image:https://travis-ci.com/saltstack-formulas/golang-formula.svg?branch=master[Travis CI Build Status]]
https://github.com/semantic-release/semantic-release[image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg[Semantic Release]]

Deploy and manage golang using Salt.

== General notes

See the full
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[SaltStack
Formulas installation and usage instructions].

If you are interested in writing or contributing to formulas, please pay
attention to the
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas[Writing
Formula Section].

If you want to use this formula, please pay attention to the `FORMULA`
file and/or `git tag`, which contains the currently released version.
This formula is versioned according to http://semver.org/[Semantic
Versioning].

If you need (non-default) configuration, please pay attention to the
`pillar.example` file and/or link:#_special_notes[Special notes] section.

See
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning[Formula
Versioning Section] for more details.

== Contributing to this repo

*Commit message formatting is significant!!*

Please see
xref:main::CONTRIBUTING.adoc[How
to contribute] for more details.

== Special notes

This formula uses (non-default) GOPATH environment variable on Unix by
default; see `go_path` key in `defaults.yaml` and `pillar.example`
files. Normally GOPATH defaults to `$HOME/go` on Unix/Darwin, `$home/go`
on Plan9, and `%USERPROFILE%\go` on Windows; another common setup is
`GOPATH=$HOME && export PATH=$PATH:$(go env GOPATH)/bin` too.

== Available states

=== `golang`

_Meta-state (This is a state that includes other states)_.

This installs the golang package, manages the golang configuration file
and then starts the associated golang service.

=== `golang.package`

This state will install the golang package only.

=== `golang.config`

This state will configure the golang service and has a dependency on
`golang.install` via include list.

=== `golang.service`

This state will start the golang service and has a dependency on
`golang.config` via include list.

=== `golang.cmd`

This is a metastate for go command tasks.

=== `golang.cmd.clean`

This state runs `go clean -i <item>...` for each item in `cmd.clean`
dict.

=== `golang.cmd.goget`

This state runs `go get <item>...` for each item in `cmd.get` dict.

=== `golang.clean`

_Meta-state (This is a state that includes other states)_.

this state will undo everything performed in the `golang` meta-state in
reverse order, i.e. stops the service, removes the configuration file
and then uninstalls the package.

=== `golang.service.clean`

This state will stop the golang service and disable it at boot time.

=== `golang.config.clean`

This state will remove the configuration of the golang service and has a
dependency on `golang.service.clean` via include list.

=== `golang.package.clean`

This state will remove the golang package and has a depency on
`golang.config.clean` via include list.

== Testing

Linux testing is done with `kitchen-salt`.

=== Requirements

* Ruby
* Docker

[source,bash]
----
$ gem install bundler
$ bundle install
$ bin/kitchen test [platform]
----

Where `[platform]` is the platform name defined in `kitchen.yml`, e.g.
`debian-9-2019-2-py3`.

=== `bin/kitchen converge`

Creates the docker instance and runs the `golang` main state, ready for
testing.

=== `bin/kitchen verify`

Runs the `inspec` tests on the actual instance.

=== `bin/kitchen destroy`

Removes the docker instance.

=== `bin/kitchen test`

Runs all of the stages above in one go: i.e. `destroy` + `converge` +
`verify` + `destroy`.

=== `bin/kitchen login`

Gives you SSH access to the instance for manual testing.

== Testing with Vagrant

Windows/FreeBSD/OpenBSD testing is done with `kitchen-salt`.

=== Requirements

* Ruby
* Virtualbox
* Vagrant

=== Setup

[source,bash]
----
$ gem install bundler
$ bundle install --with=vagrant
$ bin/kitchen test [platform]
----

Where `[platform]` is the platform name defined in
`kitchen.vagrant.yml`, e.g. `windows-81-latest-py3`.

=== Note

When testing using Vagrant you must set the environment variable
`KITCHEN_LOCAL_YAML` to `kitchen.vagrant.yml`. For example:

[source,bash]
----
$ KITCHEN_LOCAL_YAML=kitchen.vagrant.yml bin/kitchen test      # Alternatively,
$ export KITCHEN_LOCAL_YAML=kitchen.vagrant.yml
$ bin/kitchen test
----

Then run the following commands as needed.

=== `bin/kitchen converge`

Creates the Vagrant instance and runs the `golang` main states, ready
for testing.

=== `bin/kitchen verify`

Runs the `inspec` tests on the actual instance.

=== `bin/kitchen destroy`

Removes the Vagrant instance.

=== `bin/kitchen test`

Runs all of the stages above in one go: i.e. `destroy` + `converge` +
`verify` + `destroy`.

=== `bin/kitchen login`

Gives you RDP/SSH access to the instance for manual testing.
